### ISSUE TITLE
Does not build as part of a project in Android Studio.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/awaitility#20]
```
What steps will reproduce the problem?

1. Add the line "compile 'com.jayway.awaitility:awaitility-groovy:1.6.3'" to 
dependencies in an Android build.gradle.
2. Attempt to build the project.


What is the expected output? What do you see instead?

Expected nothing to happen as awaitility is not yet referenced from the tests.

Instead I get a build error:

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/chris/Android/Sdk/build-tools/21.1.2/dx --dex --no-optimize --output /home/chris/AndroidStudioProjects/androidmdt/app/build/intermediates/dex/debug --input-list=/home/chris/AndroidStudioProjects/androidmdt/app/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
  		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
  		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
  		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

The build error goes away when I remove the dependency on awaitility.

I also get repeated warnings when awaitility is a dependency:

Warning:Ignoring InnerClasses attribute for an anonymous inner class
(net.sf.cglib.util.StringSwitcher$Generator$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.


What version of the product are you using? On what operating system?

awaitility 1.6.3
android studio 1.2
java 1.8.0_40-b25 amd64
ubuntu 14.04 x86_64


```

Original issue reported on code.google.com by `cms...@gmail.com` on 14 May 2015 at 12:58

**Comment by johanhaleby** [comment]
```
Are you using it in an Android project?
```

Original comment by `johan.ha...@gmail.com` on 27 Jun 2015 at 5:03

**Comment by johanhaleby** [comment]
```
Yes, I was trying to use it in an Android project.
```

Original comment by `cms...@gmail.com` on 28 Jun 2015 at 7:40

**Comment by jdrider** [comment]
This is not a bug in the library.  The error above occurs when the dex limit is reached.  The app needs to employ Proguard or MultiDex to have more than 65k methods.

**Comment by johanhaleby** [comment]
Thanks for letting us know
