### ISSUE TITLE
Problem with Awaitility and greaterThan matcher

### ISSUE THREAD

**Issue by johanhaleby** [jayway/awaitility#25]
```
I'm getting the following message:

java.util.concurrent.TimeoutException: 
com.test.AwaitilityTest.recievedMessageCount Callable expected a value greater 
than or equal to <7000> but was <7901> within 1 seconds.
	at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:82)
	at com.jayway.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:50)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:560)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:412)

What steps will reproduce the problem?
1. awaitility 1.3.3, junit 4.8.1, hamcrest-core 1.1, hamcrest-library
2. Using a Netty Client Server app to send messages asynchronously. Checking 
Server for messages received.
3. with().pollInterval(500, 
MILLISECONDS).and().timeout(1,SECONDS).await().until(recievedMessageCount(channe
lAddress), greaterThan(7000));

I have tried Matchers greaterThan and greaterThanOrEqualTo but both fail 
intermitentantly even if the value IS greater than the value expected. 

```

Original issue reported on code.google.com by `desmond.kirrane` on 16 Jan 2012 at 6:34

**Comment by johanhaleby** [comment]
```
Hmm I've used greaterThan successfully with awaitility many times. Would it be 
possible for you to create a small example that demonstrates the issue?
```

Original comment by `johan.ha...@gmail.com` on 27 Jan 2012 at 9:46

**Comment by johanhaleby** [comment]
```
Perhaps it's related to issue 12 that has been resolved in trunk. A new version 
will probably be released quite soon.
```

Original comment by `johan.ha...@gmail.com` on 8 Feb 2012 at 7:12

**Comment by johanhaleby** [comment]
```
The new version is now released. Please try it out and see if this is still an 
issue.
```

Original comment by `johan.ha...@gmail.com` on 13 Feb 2012 at 9:24

**Comment by johanhaleby** [comment]
```
Same issue with Awaitility 1.3.4. I'll try put get some time to try pull out a 
small example to demonstrate the issue.

AwaitilityTest.recievedMessageCount Callable expected a value greater than 
<7000> but was <8474> within 1 seconds.
java.util.concurrent.TimeoutException: 

AwaitilityTest.recievedMessageCount Callable expected a value greater than 
<7000> but was <8474> within 1 seconds.
	at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:82)
	at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:82)
	at com.jayway.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:50)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:560)
	at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:412)
	at AwaitilityTest.testSyncMessageTiming(AwaitilityTest.java:85)
```

Original comment by `desmond.kirrane` on 16 Feb 2012 at 4:31

**Comment by johanhaleby** [comment]
```
Yes please do so so that we can try to fix it.
```

Original comment by `johan.ha...@gmail.com` on 17 Feb 2012 at 7:36
* Changed state: **Accepted**

**Comment by vbauer** [comment]
Any news with this issue? It looks like I have the same problem:
```
[testRun] org.awaitility.core.ConditionFactory.untilAtomic Callable expected a value greater than <0> but <4> was greater than <0> within 300 milliseconds.
```

**Comment by johanhaleby** [comment]
Could you please post an example that demonstrates the issue you're having?

**Comment by develeper84** [comment]
I am also having same issue. Can somebody help me.

    @Autowired
    private Testing testing;

   @Autowired
    private JmsTemplate jmsTemplate;

    @Test
    public void test() throws Exception {
        jmsTemplate.convertAndSend(queue, "message", message -> {
            message.setStringProperty(Class1.S, "s");
            message.setStringProperty(Class1.CT, "ct");
            return message;
        });
        with().pollInterval(500,
                MILLISECONDS).and().timeout(1, SECONDS).await().until(mockInteractionCount(testing), equalTo(2));

        verify(cxmlWriter, times(1)).saveFile(any(), any(), any());
        verify(cxmlWriter, times(1)).saveFile(eq("source"), eq("contentType"), eq("message"));
        assertTrue(true); //for sonar
    }

    private Callable<Integer> mockInteractionCount(Object obj) throws InterruptedException {
        return () -> Mockito.mockingDetails(obj).getInvocations().size();
    }

org.awaitility.core.ConditionTimeoutException: Lambda expression in package.TestClassTests that uses java.lang.Object: expected <2> but was <0> within 10 seconds.

**Comment by johanhaleby** [comment]
Maybe try `equalTo(2L)` instead and see if that works?

**Comment by develeper84** [comment]
got Error

org.awaitility.core.ConditionTimeoutException: Lambda expression in package.TestClassTests that uses java.lang.Object: expected <2L> but was <2> within 1 seconds.

**Comment by johanhaleby** [comment]
@develeper84 Maybe it's due to Hamcrest is differentiating between primitive and boxed values, try `equalTo(new Integer(2))`.

**Comment by develeper84** [comment]
I made this change and still getting same error.
     
   with().pollInterval(500,
                MILLISECONDS).and().timeout(1, SECONDS).await().until(mockInteractionCount(cxmlWriter), equalTo(new Integer(2)));

Stacktrace
org.awaitility.core.ConditionTimeoutException: Lambda expression in package.TestClassTests that uses java.lang.Object: expected <2> but was <0> within 1 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:136)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:89)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:840)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:619)

**Comment by johanhaleby** [comment]
I don't know what's going on, I've written a [small test](https://github.com/awaitility/awaitility/blob/master/awaitility/src/test/java/org/awaitility/BoxingTest.java) where I've tried to reproduce this but I fail to do so:

```java
@Test
    public void non_primitive_numbers_are_successfully_matched_against_their_primitive_counter_parts() {
        AtomicInteger ai = new AtomicInteger(0);

        new Thread(() -> {
            try {
                Thread.sleep(400);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            ai.set(2);
        }).start();

        await().until(() -> new Integer(ai.get()), equalTo(2));
    }
```

What's the difference?

**Comment by jbee** [comment]
Bug certainly still exists. I have 1 thread incrementing a counter every 5ms, and the test checking that after 40ms it is >= 4. This fails about 5% of the time but in the error message the actual value always is >= 4. The issue is obviously that the actual value is read again for description after the comparison has been made. What I cannot say is where as it does not occur when I debug which is most likely due to the delicate timing.
