### ISSUE TITLE
Parallel test execution with MethodCallRecorder impossible - IllegalStateException

### ISSUE THREAD

**Issue by tombujok** [jayway/awaitility#28]
Why does the MethodCallRecorder use static fields to record the lastTarget?

I frequently get Method call not recorded error message. Could it be connected to the MethodCallRecorder static fields and parallel test execution?

```
java.lang.IllegalStateException: No method call has been recorded. Perhaps the method was final?
	at com.jayway.awaitility.core.MethodCallRecorder.getLastTarget(MethodCallRecorder.java:68)
	at com.jayway.awaitility.core.ConditionFactory.untilCall(ConditionFactory.java:363)
	at com.hazelcast.concurrent.lock.ConditionBasicTest.testSignalWithMultipleWaiters(ConditionBasicTest.java:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tombujok** [comment]
Digging into the code there's a race here:
```
public <T> T untilCall(T ignore, final Matcher<? super T> matcher) {
        final MethodCaller<T> supplier = new MethodCaller<T>(MethodCallRecorder.getLastTarget(), MethodCallRecorder
                .getLastMethod(), MethodCallRecorder.getLastArgs());
        MethodCallRecorder.reset();
        final ProxyHamcrestCondition<T> proxyCondition = new ProxyHamcrestCondition<T>(supplier, matcher, generateConditionSettings());
        return until(proxyCondition);
    }
```

Why is this taken from the static field?
`MethodCallRecorder.getLastMethod(), MethodCallRecorder.getLastArgs());`
